### ISSUE TITLE
webhook

### ISSUE THREAD

**Issue by ssiwinter** [hyunamy/comfy-ui-on-complete-email-me#3]
Hi would it be possible to change from email method to sendind message via webhook? I have NTFY server that normally run all my notification but it is not good if you generate huge amounts of images.

Thanks

**Comment by bobddadoo** [comment]
As you suggested, I created the OnCompleteWebhook node. Please update and check it out.

**Comment by hyunamy** [comment]
> Hi would it be possible to change from email method to sendind message via webhook? I have NTFY server that normally run all my notification but it is not good if you generate huge amounts of images.
> 
> Thanks

Did you checked that i made webhook nod?
